### ISSUE TITLE
Windows arm64 support

### ISSUE THREAD

**Issue by adamsitnik** [microsoft/clrmd#1050]
Are there any plans for adding Windows arm64 support?

Currently I can't attach to an arm64 process on Windows due to missing DAC.

Context: we have recently implemented an arm64 disassembler for BenchmarkDotNet and it works great on Linux, but does not on Windows. It would be nice to have it working too.

**Comment by leculver** [comment]
What's the error you are getting?  AFAIK this should work, but I don't have an arm64 machine handy.  All of the requisite pieces should be there, but I've never tested it.

**Comment by adamsitnik** [comment]
```log
System.IO.FileNotFoundException: 'Could not find matching DAC for this runtime.'
   at Microsoft.Diagnostics.Runtime.ClrInfo.CreateRuntime()
```

**Comment by leculver** [comment]
Sorry, I've been heads down for the last few weeks.  I'm now a bit more free to look at issues.


> ```
> System.IO.FileNotFoundException: 'Could not find matching DAC for this runtime.'
>    at Microsoft.Diagnostics.Runtime.ClrInfo.CreateRuntime()
> ```

If this is a crash dump, can you please share it with me offline?

I assume this is a live process though, right?  Is there an Arm64 machine you can share credentials with me (offline) so I can go investigate this with a debugger?

**Comment by k15tfu** [comment]
@leculver Hi! I faced with the same issue, this happens because of:
https://github.com/microsoft/clrmd/blob/0c46ba9ce162de1cfc124379c0d9cde99ed4206f/src/Microsoft.Diagnostics.Runtime/DataReaders/Windows/WindowsProcessDataReader.cs#L134

, so the corresponding `DebugLibraryInfo` for `shared\Microsoft.NETCore.App\7.0.10\mscordaccore.dll` has `TargetArchitecture` which is equal to `Amd64`:
https://github.com/microsoft/clrmd/blob/0c46ba9ce162de1cfc124379c0d9cde99ed4206f/src/Microsoft.Diagnostics.Runtime/ClrInfo.cs#L149

Besides, looks like `WindowsProcessDataReader.GetThreadContext()` should also support `ARM64Context`:
https://github.com/microsoft/clrmd/blob/0c46ba9ce162de1cfc124379c0d9cde99ed4206f/src/Microsoft.Diagnostics.Runtime/DataReaders/Windows/WindowsProcessDataReader.cs#L202-L227

Please tell me if you need anything else.

**Comment by leculver** [comment]
Thank you!  This is extremely helpful.
