### ISSUE TITLE
Unable to attach to macOS process

### ISSUE THREAD

**Issue by n8ta-msft** [microsoft/clrmd#1230]
This code does not seem to work on a dotnet project out of the box. 
```
using DataTarget dataTarget = DataTarget.AttachToProcess(Process.GetCurrentProcess().Id, true);
```
Fails with 
```
Unhandled exception. Microsoft.Diagnostics.Runtime.ClrDiagnosticsException: Could not attach to process 55656, errno: 1
   at Microsoft.Diagnostics.Runtime.MacOS.MacOSProcessDataReader..ctor(Int32 processId, Boolean suspend)
   at Microsoft.Diagnostics.Runtime.DataTarget.AttachToProcess(Int32 processId, Boolean suspend)
   at Program.Main() in /Users/n8ta/SIG8/test_app/Program.cs:line 41
```
I have a repro project here https://github.com/n8ta-msft/clrmd-repro for arm64 macOS.
I suspect I need to sign with some specific entitlements but I have not been able to figure out which.

**Comment by hoyosjs** [comment]
The problem might really be that the `MacOSProcessDataReader` will use `ptrace` given `suspend: true`. See https://lkml.org/lkml/2006/8/31/24. The scenario has been reported as largely affecting self-diagnostic ptrace, but the change was intentional. The change is old enough it's likely to have been ported to the ptrace implementation that macOS uses.

**Comment by leculver** [comment]
Closing as a duplicate of #1034.  This is still an issue, but only tracking it in one place.
