### ISSUE TITLE
InvalidOperationException in DesktopRuntimeBase.get_AppDomains()

### ISSUE THREAD

**Issue by discostu105** [Microsoft/clrmd#157]
I'm using CLRMD 1.0 and since recently I'm seeing this exception (not for all crash dumps):

```
INFO: created runtime with version v2.0.50727.8789
ERROR: WinDbgAnalyzer failed: System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.Diagnostics.Runtime.DacInterface.CallableCOMWrapper..ctor(RefCountedFreeLibrary library, Guid& desiredInterface, IntPtr pUnknown)
   at Microsoft.Diagnostics.Runtime.Desktop.DesktopModule..ctor(DesktopRuntimeBase runtime, UInt64 address, IModuleData data, String name, String assemblyName)
   at Microsoft.Diagnostics.Runtime.Desktop.DesktopRuntimeBase.GetModule(UInt64 module)
   at Microsoft.Diagnostics.Runtime.Desktop.DesktopRuntimeBase.InitDomain(UInt64 domain, String name)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Diagnostics.Runtime.Desktop.DesktopRuntimeBase.CreateAppDomainList()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.Diagnostics.Runtime.Desktop.DesktopRuntimeBase.get_AppDomains()
   at SuperDump.Analyzers.SystemAnalyzer.GetAppDomains() in C:\workspaces\priv\superdump-internal.git\src\SuperDump\Analyzers\SystemAnalyzer.cs:line 97
   at SuperDump.Analyzers.SystemAnalyzer.InitSystemInfo() in C:\workspaces\priv\superdump-internal.git\src\SuperDump\Analyzers\SystemAnalyzer.cs:line 34
   at SuperDump.Analyzers.SystemAnalyzer..ctor(DumpContext context) in C:\workspaces\priv\superdump-internal.git\src\SuperDump\Analyzers\SystemAnalyzer.cs:line 23
   at SuperDump.Program.<>c__DisplayClass7_0.<RunAnalysis>b__1() in C:\workspaces\priv\superdump-internal.git\src\SuperDump\Program.cs:line 79
   at SuperDump.Program.RunSafe(String name, Action action) in C:\workspaces\priv\superdump-internal.git\src\SuperDump\Program.cs:line 213
```

Cannot share the dump file for privacy reasons.

Here is the code calling CLRMD: https://github.com/Dynatrace/superdump/blob/master/src/SuperDump/Analyzers/SystemAnalyzer.cs#L97

**Comment by discostu105** [comment]
For a different crash dump I get a similar (yet different) stacktrace:

```
ERROR: WinDbgAnalyzer failed: System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.Diagnostics.Runtime.DacInterface.CallableCOMWrapper..ctor(RefCountedFreeLibrary library, Guid& desiredInterface, IntPtr pUnknown)
   at Microsoft.Diagnostics.Runtime.Desktop.LegacyRuntime.GetMetadataImport(UInt64 module)
   at Microsoft.Diagnostics.Runtime.Desktop.DesktopModule.GetMetadataImport()
   at Microsoft.Diagnostics.Runtime.Desktop.DesktopMethod.Create(DesktopRuntimeBase runtime, IMethodDescData mdData)
   at Microsoft.Diagnostics.Runtime.Desktop.DesktopStackFrame.InitMethod(UInt64 md)
   at Microsoft.Diagnostics.Runtime.Desktop.LegacyRuntime.GetStackFrame(DesktopThread thread, UInt64 ip, UInt64 sp, UInt64 frameVtbl)
   at Microsoft.Diagnostics.Runtime.Desktop.DesktopRuntimeBase.<EnumerateStackFrames>d__82.MoveNext()
   at Microsoft.Diagnostics.Runtime.Desktop.DesktopThread.get_StackTrace()
   at SuperDump.CombinedStackTrace.GetManagedStackTrace(UInt32 osThreadId) in C:\workspaces\priv\superdump-internal.git\src\SuperDump\CombinedStackTrace.cs:line 114
   at SuperDump.CombinedStackTrace.GetCompleteStackTrace() in C:\workspaces\priv\superdump-internal.git\src\SuperDump\CombinedStackTrace.cs:line 138
   at SuperDump.Analyzers.ThreadAnalyzer.GetCombinedStackTraces() in C:\workspaces\priv\superdump-internal.git\src\SuperDump\Analyzers\ThreadAnalyzer.cs:line 210
   at SuperDump.Analyzers.ThreadAnalyzer..ctor(DumpContext context) in C:\workspaces\priv\superdump-internal.git\src\SuperDump\Analyzers\ThreadAnalyzer.cs:line 35
   at SuperDump.Program.<>c__DisplayClass7_0.<RunAnalysis>b__3() in C:\workspaces\priv\superdump-internal.git\src\SuperDump\Program.cs:line 105
   at SuperDump.Program.RunSafe(String name, Action action) in C:\workspaces\priv\superdump-internal.git\src\SuperDump\Program.cs:line 213
```

meta-info
```
--- General System Info ---
Dump was taken at: 12/6/2018 3:06:38 AM UTC +01:00:00
System up-time: Could not be obtained.
OS version: kernel32.dll version: 6.1.7601.24231 (win7sp1_ldr.180810-0600)
Process architecture (read from dump): Amd64
Number of logical processing units in target system: 24

--- CLR version list ---
Found CLR Version:v2.0.50727.8793
Filesize:  9A0000
Timestamp: 5B554B14
Dac File:  mscordacwks_Amd64_Amd64_2.0.50727.8793.dll
```

Kind of looks like the same thing.

**Comment by leculver** [comment]
Thank you for the report.  Do you only see this on V2 runtimes?  Or have you seen it on v4 runtimes as well?

**Comment by discostu105** [comment]
I've not found this particular error in a V4 runtime yet. However, I can say that most analysis runs work just fine in V2 and also in V4 runtimes.

**Comment by leculver** [comment]
Thanks for the report!  I finally figured this one out.
