### ISSUE TITLE
NullReferenceException in DacInterface.CallableCOMWrapper.Release()

### ISSUE THREAD

**Issue by discostu105** [Microsoft/clrmd#158]
I'm using CLRMD 1.0 and since recently I'm seeing this exception (not for all crash dumps):

```
INFO: created runtime with version v2.0.50727.8789
ERROR: Exception creating CLR Runtime
ERROR: Object reference not set to an instance of an object.
   at Microsoft.Diagnostics.Runtime.DacInterface.CallableCOMWrapper..ctor(RefCountedFreeLibrary library, Guid& desiredInterface, IntPtr pUnknown)
   at Microsoft.Diagnostics.Runtime.Desktop.DesktopModule..ctor(DesktopRuntimeBase runtime, UInt64 address, IModuleData data, String name, String assemblyName)
   at Microsoft.Diagnostics.Runtime.Desktop.DesktopRuntimeBase.GetModule(UInt64 module)
   at Microsoft.Diagnostics.Runtime.Desktop.LegacyGCHeap.GetTypeByMethodTable(UInt64 mt, UInt64 cmt, UInt64 obj)
   at Microsoft.Diagnostics.Runtime.Desktop.DesktopGCHeap..ctor(DesktopRuntimeBase runtime)
   at Microsoft.Diagnostics.Runtime.Desktop.DesktopRuntimeBase.CreateHeap()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at SuperDump.Program.SetupCLRRuntime() in C:\workspaces\priv\superdump-internal.git\src\SuperDump\Program.cs:line 176
```
Cannot share the dump file for privacy reasons.

Here is the code calling CLRMD: https://github.com/Dynatrace/superdump/blob/master/src/SuperDump/Program.cs#L164

**Comment by leculver** [comment]
Thanks for the report.  Looks like another v2 issue.  I'll do some better testing with that runtime and see what we find.
