### ISSUE TITLE
Throw better exception in DataTarget.LoadCrashDump when it is passed a coredump

### ISSUE THREAD

**Issue by tanaka-takayoshi** [microsoft/clrmd#170]
When loading the dump file with `DataTarget.LoadCrashDump` method, it reported the error.

```
$ dotnet  run

Unhandled Exception: System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'parameter #2': Invalid managed/unmanaged type combination (Marshaling to and from COM interface pointers isn't supported).
   at Microsoft.Diagnostics.Runtime.DbgEngDataReader.DebugCreate(Guid& InterfaceId, Object& Interface)
   at Microsoft.Diagnostics.Runtime.DbgEngDataReader.CreateIDebugClient() in /_/src/Microsoft.Diagnostics.Runtime/DbgEngDataReader.cs:line 164
   at Microsoft.Diagnostics.Runtime.DbgEngDataReader..ctor(String dumpFile) in /_/src/Microsoft.Diagnostics.Runtime/DbgEngDataReader.cs:line 51
   at Microsoft.Diagnostics.Runtime.DataTarget.LoadCrashDump(String fileName) in /_/src/Microsoft.Diagnostics.Runtime/datatarget.cs:line 67
   at ClrMDExample.Program.Main(String[] args) in /home/clouduser/ClrMdExample/Program.cs:line 11
```

Here is the runtime info.

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.100
 Commit:    b9f2fa0ca8

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.100/

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.2.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Executed program.
```
using System;
using System.Linq;
using Microsoft.Diagnostics.Runtime;

namespace ClrMDExample
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var target = DataTarget.LoadCrashDump(@"/tmp/coredump.2971"))
            {
                foreach (var version in target.ClrVersions)
                {
                    Console.WriteLine("Found CLR Version:" + version.Version.ToString());
		}
	    }

	}
     }
}
```

The `/tmp/coredump.2971` is created with the same dotnet runtime on the same host.

**Comment by leculver** [comment]
Use DataTarget.LoadCoreDump on linux.

I will throw a better exception in the future.

**Comment by tanaka-takayoshi** [comment]
`DataTarget.LoadCoreDump` works. Thanks!

**Comment by leculver** [comment]
I am leaving this bug open to track throwing a better exception here.  Thank you for the report!
