### ISSUE TITLE
ArgumentNullException with cache* element in symbol path

### ISSUE THREAD

**Issue by d-schneider** [microsoft/clrmd#267]
Since updating to version 1.0.5 of the nuget package, we get an ArgumentNullException for some dumps when the symbol path contains a cache* element.
If we remove the cache* element from the symbol path it works again.

Symbol Path:
```
cache*c:\symbols;srv*c:\symbols*\\mysymstore1;srv*c:\symbols*\\mysymstore2;srv*c:\symbols*https://msdl.microsoft.com/download/symbols
```

This could be related to PR #235. It seems that Cache SymPathElements are not always handled (e.g. in line 62 of the DefaultSymbolLocator. However, I did not verify that this code part is the issue)

Here is the stack trace:
```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.Diagnostics.Runtime.Utilities.DefaultSymbolLocator.<SearchSymbolServerForFile>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Diagnostics.Runtime.Utilities.DefaultSymbolLocator.<DownloadFileWorker>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Diagnostics.Runtime.Utilities.DefaultSymbolLocator.<FindBinaryAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Diagnostics.Runtime.Utilities.DefaultSymbolLocator.<>c__DisplayClass23_0.<<PrefetchBinary>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

The project where this occured can be found at: https://github.com/Dynatrace/superdump/tree/master/src/SuperDump

**Comment by leculver** [comment]
This was fixed in 159a4e3d but I forgot to close the bug.
