### ISSUE TITLE
GCRoot tests non-deterministicly fail

### ISSUE THREAD

**Issue by leculver** [microsoft/clrmd#459]
GCRoot tests also looks to have non-deterministic failures.  This looks like a real product issue.

**Comment by NextTurn** [comment]
I'd like to take a closer look at this when I'm free. Could you share the trace logs (`GCROOTTRACE`) of test failures?

**Comment by leculver** [comment]
Sure, as soon as I have some time I want to add an infinite loop of GCRoot to `LongRunningTests`, which should reproduce the problem.  You should be able to test it locally with any flags when I do that.  Not sure if I'll get around to it today but it'll be the next thing I work on.

**Comment by leculver** [comment]
Ended up figuring out what was wrong here and fixing a few other unrelated problems along the way.

**Comment by leculver** [comment]
Still failing non-deterministicly.  Will look again tomorrow.

**Comment by NextTurn** [comment]
Nit

```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. Microsoft.Diagnostics.Runtime.AssertionException: Assertion Failed
   at Microsoft.Diagnostics.Runtime.DebugOnly.Fail(String message) in clrmd\src\Microsoft.Diagnostics.Runtime\src\Extensions\DebugOnly.cs:line 25
   at Microsoft.Diagnostics.Runtime.DebugOnly.Assert(Boolean mustBeTrue, String msg) in clrmd\src\Microsoft.Diagnostics.Runtime\src\Extensions\DebugOnly.cs:line 19
   at Microsoft.Diagnostics.Runtime.DebugOnly.Assert(Boolean mustBeTrue) in clrmd\src\Microsoft.Diagnostics.Runtime\src\Extensions\DebugOnly.cs:line 13
   at Microsoft.Diagnostics.Runtime.Utilities.CallableCOMWrapper.InitDelegateWorker[T](T& t, IntPtr entry) in clrmd\src\Microsoft.Diagnostics.Runtime\src\Utilities\COMInterop\CallableComWrapper.cs:line 107
   at Microsoft.Diagnostics.Runtime.DacInterface.SOSDac.EnumerateHandles(ClrHandleKind[] types) in clrmd\src\Microsoft.Diagnostics.Runtime\src\DacInterface\SosDac.cs:line 630
   at Microsoft.Diagnostics.Runtime.Builders.RuntimeBuilder.Microsoft.Diagnostics.Runtime.Implementation.IHeapHelpers.EnumerateDependentHandleLinks()+MoveNext() in clrmd\src\Microsoft.Diagnostics.Runtime\src\Builders\RuntimeBuilder.cs:line 504
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Diagnostics.Runtime.Implementation.ClrmdHeap.EnumerateObjectReferences(UInt64 obj, ClrType type, Boolean carefully, Boolean considerDependantHandles)+MoveNext() in clrmd\src\Microsoft.Diagnostics.Runtime\src\Implementation\ClrmdHeap.cs:line 351
   at Microsoft.Diagnostics.Runtime.GCRoot.<PathsTo>g__GetRefs|15_0(ClrObject obj, Boolean& found, LinkedListNode`1& end, <>c__DisplayClass15_0& ) in clrmd\src\Microsoft.Diagnostics.Runtime\src\Common\GCRoot.cs:line 417
   at Microsoft.Diagnostics.Runtime.GCRoot.PathsTo(ObjectSet deadEnds, Dictionary`2 knownEndPoints, ClrObject source, UInt64 target, Boolean unique, CancellationToken cancellationToken)+MoveNext() in clrmd\src\Microsoft.Diagnostics.Runtime\src\Common\GCRoot.cs:line 294
   at Microsoft.Diagnostics.Runtime.GCRoot.WorkerThread(BlockingCollection`1 queue, ConcurrentQueue`1 results, ObjectSet seen, Dictionary`2 knownEndPoints, UInt64 target, Boolean all, Boolean unique, CancellationToken cancellationToken) in clrmd\src\Microsoft.Diagnostics.Runtime\src\Common\GCRoot.cs:line 182
   at Microsoft.Diagnostics.Runtime.GCRoot.<>c__DisplayClass11_1.<EnumerateGCRoots>b__0() in clrmd\src\Microsoft.Diagnostics.Runtime\src\Common\GCRoot.cs:line 122
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by leculver** [comment]
That assert should have been fixed in https://github.com/microsoft/clrmd/commit/31c031acd63f1dd00b15e0cb3d7e4dff88d3e9c9#diff-a7deaa30b8ecd20f5c1994f44c495387 ?

Let me know if you see that still.

**Comment by leculver** [comment]
Oh, no that introduced the assert.

The issue is that we can race to create the delegate on multiple threads.  That's fine, but the assert will trigger if another thread raced to fill the value.

Since we only call InitDelegateWorker in one place, there's no reason to assert there.

**Comment by NextTurn** [comment]
Another test report:

```
Test Name:	Microsoft.Diagnostics.Runtime.Tests.GCRootTests.GCRoots
Test FullName:	Microsoft.Diagnostics.Runtime.Tests.Microsoft.Diagnostics.Runtime.Tests.GCRootTests.Microsoft.Diagnostics.Runtime.Tests.GCRootTests.GCRoots
Test Source:	clrmd\src\Microsoft.Diagnostics.Runtime.Tests\src\GCRootTests.cs : line 213
Test Outcome:	Failed
Test Duration:	0:00:00

Test Name:	Microsoft.Diagnostics.Runtime.Tests.GCRootTests.GCRoots
Test Outcome:	Failed
Result StackTrace:	
at Microsoft.Diagnostics.Runtime.Tests.GCRootTests.AssertPathIsCorrect(ClrHeap heap, ImmutableArray`1 path, UInt64 source, UInt64 target) in clrmd\src\Microsoft.Diagnostics.Runtime.Tests\src\GCRootTests.cs:line 374
   at Microsoft.Diagnostics.Runtime.Tests.GCRootTests.CheckRootPaths(ClrHeap heap, UInt64 target, GCRootPath[] rootPaths, Boolean mustContainStatic) in clrmd\src\Microsoft.Diagnostics.Runtime.Tests\src\GCRootTests.cs:line 250
   at Microsoft.Diagnostics.Runtime.Tests.GCRootTests.GCRootsImpl(GCRoot gcroot, ClrHeap heap, UInt64 target, Int32 parallelism, Boolean unique) in clrmd\src\Microsoft.Diagnostics.Runtime.Tests\src\GCRootTests.cs:line 242
   at Microsoft.Diagnostics.Runtime.Tests.GCRootTests.GCRootsImpl(GCRoot gcroot) in clrmd\src\Microsoft.Diagnostics.Runtime.Tests\src\GCRootTests.cs:line 229
   at Microsoft.Diagnostics.Runtime.Tests.GCRootTests.GCRoots() in clrmd\src\Microsoft.Diagnostics.Runtime.Tests\src\GCRootTests.cs:line 220
Result Message:	
Assert.Contains() Failure
Not found: SingleRef 39c3010
In value:  <EnumerateObjectReferences>d__50 [DoubleRef 39c2e60]
```

**Comment by NextTurn** [comment]
Oops, I accidentally closed this. This may not have been fully resolved.

**Comment by leculver** [comment]
No worries!

Yep this is still an issue.  I *think* the underlying problem with the test here is that we throw all GC roots into a parallel queue and sometimes the handle roots win, and sometimes the stack roots win...but I haven't tested it yet.  This would be "fixable" by making the parallel gcroot code process _all_ handle roots first and when they are done then process all other roots.

However I may just have a bug in this code, it's a really tough algorithm to get right in parallel.  I'm leaving this issue open for now.

**Comment by leculver** [comment]
I did a bit of research here.  There's still two problems here:

**Static roots:**  None of the GCRoot code currently favors pinned object handles (including static variables) as it should.  This isn't something that the API guarantees, but it's a _really_ nice property to have since FQ roots and the majority of stack roots are short-lived.  The fix here would essentially be processing all handle roots first,
