### ISSUE TITLE
"Unknown custom metadata item kind: 6" in PdbFunction.ReadCustomMetadata

### ISSUE THREAD

**Issue by herebebeasties** [Microsoft/clrmd#49]
Using the example code from `FileAndLineNumbers` I get the following:

```
Unhandled Exception: Microsoft.Diagnostics.Runtime.Utilities.Pdb.PdbDebugException: Unknown custom metadata item kind: 6
   at Microsoft.Diagnostics.Runtime.Utilities.Pdb.PdbFunction.ReadCustomMetadata(BitAccess bits)
   at Microsoft.Diagnostics.Runtime.Utilities.Pdb.PdbFunction..ctor(ManProcSym proc, BitAccess bits)
   at Microsoft.Diagnostics.Runtime.Utilities.Pdb.PdbFunction.LoadManagedFunctions(BitAccess bits, UInt32 limit, Boolean readStrings)
   at Microsoft.Diagnostics.Runtime.Utilities.Pdb.PdbFile.LoadFuncsFromDbiModule(BitAccess bits, DbiModuleInfo info, Dictionary`2 names, List`1 funcList, Boolean readStrings, MsfDirectory dir, Dictionary`2 nameIndex, PdbStreamHelper reader, Dictionary`2 sources)
   at Microsoft.Diagnostics.Runtime.Utilities.Pdb.PdbFile.LoadFunctions(Stream read, BitAccess bits, Boolean readAllStrings, Int32& ver, Int32& sig, Int32& age, Guid& guid, IEnumerable`1& sources)
   at Microsoft.Diagnostics.Runtime.Utilities.Pdb.PdbReader.Init(Stream pdbStream)
   at Microsoft.Diagnostics.Runtime.Utilities.Pdb.PdbReader..ctor(String fileName)
```

https://github.com/jbevain/cecil/issues/186 suggests that this might be fixed with this:
https://github.com/jbevain/cecil/commit/d33d51499a0c19238f41db5a06ab01b1f7aae210

**Comment by Zero3** [comment]
I'm getting the same error, but with kind 7 :/.

**Comment by leculver** [comment]
This was fixed a while back but I didn't close the issue.  Overall I recommend using Cecil itself instead of my Pdb reader...

ClrMD was created a long time ago (before NuGet) and needed to carry a lot of its dependencies instead of using ones out there.  At this point though it's probably better to not use the utilities here unless you have to.
