### ISSUE TITLE
ClrMD on Linux throws IOException

### ISSUE THREAD

**Issue by damageboy** [microsoft/clrmd#557]
Using .NET Core 3.1.101:

```
 $ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     clear-linux-os
 OS Version:  32570
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/dmg/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.801 [/home/dmg/dotnet/sdk]
  2.2.401 [/home/dmg/dotnet/sdk]
  3.0.100 [/home/dmg/dotnet/sdk]
  3.1.100 [/home/dmg/dotnet/sdk]
  3.1.101 [/home/dmg/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [/home/dmg/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [/home/dmg/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [/home/dmg/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [/home/dmg/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/home/dmg/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [/home/dmg/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/home/dmg/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [/home/dmg/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [/home/dmg/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/home/dmg/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/home/dmg/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/home/dmg/dotnet/shared/Microsoft.NETCore.App]
```

Running JitDasm with ClrMD 1.1.61812 throws an `IOException`:

```bash
 $ ./JitDasm -l /tmp/hw/linux-x64/hw.dll
System.IO.IOException: I/O error occurred.
   at Microsoft.Diagnostics.Runtime.Linux.Reader.Read[T](Int64 position)
   at Microsoft.Diagnostics.Runtime.Linux.ElfFile..ctor(Reader reader, Int64 position, Boolean isVirtual)
   at Microsoft.Diagnostics.Runtime.Linux.LinuxLiveDataReader.GetVersionInfo(UInt64 baseAddress, VersionInfo& version)
   at Microsoft.Diagnostics.Runtime.ModuleInfo.get_Version()
   at Microsoft.Diagnostics.Runtime.DataTargetImpl.InitVersions()
   at Microsoft.Diagnostics.Runtime.DataTargetImpl.get_ClrVersions()
   at JitDasm.Program.GetMethodsToDisassemble(Int32 pid, String moduleName, MemberFilter typeFilter, MemberFilter methodFilter, Boolean heapSearch) in /home/dmg/projects/public/JitDasm/JitDasm/Program.cs:line 270
   at JitDasm.Program.Main(String[] args) in /home/dmg/projects/public/JitDasm/JitDasm/Program.cs:line 53
```

Reverting JitDasm to ClrMD to 1.1.57004 solves the issue:

```bash
$ ./JitDasm -l /tmp/hw/linux-x64/hw.dll
; ================================================================================
; hw.Program..ctor()
; 30 (0x1E) bytes
; 10 (0xA) instructions

00007F3FD771FE20 55                   push    rbp
00007F3FD771FE21 4883EC10             sub     rsp,10h
00007F3FD771FE25 488D6C2410           lea     rbp,[rsp+10h]
00007F3FD771FE2A 48897DF8             mov     [rbp-8],rdi

00007F3FD771FE2E 488B7DF8             mov     rdi,[rbp-8]
00007F3FD771FE32 E85102FEFF           call    System.Object..ctor()

00007F3FD771FE37 90                   nop
00007F3FD771FE38 488D6500             lea     rsp,[rbp]
00007F3FD771FE3C 5D                   pop     rbp
00007F3FD771FE3D C3                   ret

; ================================================================================
; hw.Program.Main(System.String[])
; 39 (0x27) bytes
; 11 (0xB) instructions

00007F3FD7720110 55                   push    rbp
00007F3FD7720111 4883EC10             sub     rsp,10h
00007F3FD7720115 488D6C2410           lea     rbp,[rsp+10h]
00007F3FD772011A 48897DF8             mov     [rbp-8],rdi

;             Console.WriteLine("Hello World!");
00007F3FD772011E 48BFA07500C03F7F0000 mov     rdi,7F3FC00075A0h
00007F3FD7720128 488B3F               mov     rdi,[rdi]
00007F3FD772012B E880F6FFFF           call    System.Console.WriteLine(System.String)

;         }
00007F3FD7720130 90                   nop
00007F3FD7720131 488D6500             lea     rsp,[rbp]
00007F3FD7720135 5D                   pop     rbp
00007F3FD7720136 C3                   ret
```

**Comment by NextTurn** [comment]
Fixed in #528

**Comment by damageboy** [comment]
@NextTurn Thanks for responsing!
Is there a 1.1 release planned where this will be nugetized?

**Comment by NextTurn** [comment]
There should be a new 1.1 release soon. @leculver

**Comment by leculver** [comment]
Yes, I plan to build one tomorrow assuming everything goes to plan.  (Sometimes our build system for producing new builds gives me trouble.)

**Comment by leculver** [comment]
The internal build server producing signed builds is, in fact, broken again.  I'm working on fixing it now.  Not sure if I'll get a package out this week.  =/

**Comment by leculver** [comment]
I've published this build which should contain the fix:  https://www.nuget.org/packages/Microsoft.Diagnostics.Runtime/1.1.116301.  It will show up in visual studio a few hours from now.  Please let me know if you have more problems.

I'm still not able to publish 2.0-beta builds but we are working on that.
