### ISSUE TITLE
Several issues in Debug build

### ISSUE THREAD

**Issue by swift-kim** [microsoft/clrmd#607]
The following issues only occur in the Debug build. Maybe some are not reproducible on other platforms than Tizen armel.

1. (Linux) False-positive assertion when a memory mapped file path contains a space
https://github.com/microsoft/clrmd/blob/61f5f98030789f428d45b50a54a8242b6a5e9c12/src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs#L415-L419

    ```
    Unhandled exception. Microsoft.Diagnostics.Runtime.AssertionException: Unknown data format
       at Microsoft.Diagnostics.Runtime.DebugOnly.Fail(String message) in E:\public\clrmd2.0\src\Microsoft.Diagnostics.Runtime\src\Extensions\DebugOnly.cs:line 25
       at Microsoft.Diagnostics.Runtime.Linux.LinuxLiveDataReader.LoadMemoryMap() in E:\public\clrmd2.0\src\Microsoft.Diagnostics.Runtime\src\Linux\LinuxLiveDataReader.cs:line 417
       ...
    ```

2. Casting failure in GetMethodTableSlot()
https://github.com/microsoft/clrmd/blob/31c031acd63f1dd00b15e0cb3d7e4dff88d3e9c9/src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosDac.cs#L127-L128

    When `slot` is -1 (I don't know how this is possible), it turns into an OverflowException.
    ```
    Unhandled exception. System.OverflowException: Arithmetic operation resulted in an overflow.
       at Microsoft.Diagnostics.Runtime.DacInterface.SOSDac.GetMethodTableSlot(UInt64 mt, Int32 slot) in E:\public\clrmd2.0\src\Microsoft.Diagnostics.Runtime\src\DacInterface\SosDac.cs:line 128
       at Microsoft.Diagnostics.Runtime.Builders.MethodBuilder.Init(SOSDac sos, UInt64 methodDesc, IMethodHelpers helpers) in E:\public\clrmd2.0\src\Microsoft.Diagnostics.Runtime\src\Builders\MethodBuilder.cs:line 36
    ```

    Although this can be easily escaped by wrapping with `unchecked` or adding a parameter validation (kind of `return 0 if slot < 0`), maybe I have to first figure out why `slot` is -1.

3. Huge DataOffset in ResourceEntry.GetChildren()
https://github.com/microsoft/clrmd/blob/4574409804acdf4ca346bbf8bf538a56f2b654a7/src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/ResourceEntry.cs#L136-L143

    System.OverflowException is thrown again because `entry.DataOffset` is too large or invalid.
    ```
    resourceStartFileOffset=10000 entry.DataOffset=7FFFFF80
    Unhandled exception. System.OverflowException: Arithmetic operation resulted in an overflow.
       at Microsoft.Diagnostics.Runtime.Utilities.ResourceEntry.GetChildren() in E:\public\clrmd2.0\src\Microsoft.Diagnostics.Runtime\src\Utilities\PEImage\ResourceEntry.cs:line 143
       at Microsoft.Diagnostics.Runtime.Utilities.ResourceEntry.get_Children() in E:\public\clrmd2.0\src\Microsoft.Diagnostics.Runtime\src\Utilities\PEImage\ResourceEntry.cs:line 75
       at Microsoft.Diagnostics.Runtime.Utilities.PEImage.GetFileVersionInfo() in E:\public\clrmd2.0\src\Microsoft.Diagnostics.Runtime\src\Utilities\PEImage\PEImage.cs:line 208
       at Microsoft.Diagnostics.Runtime.CoreDumpReader.CreateModuleInfo(ElfLoadedImage image) in E:\public\clrmd2.0\src\Microsoft.Diagnostics.Runtime\src\DataReaders\Core\CoreDumpReader.cs:line 114
       at Microsoft.Diagnostics.Runtime.CoreDumpReader.EnumerateModules() in E:\public\clrmd2.0\src\Microsoft.Diagnostics.Runtime\src\DataReaders\Core\CoreDumpReader.cs:line 95
       at Microsoft.Diagnostics.Runtime.DataTarget.EnumerateModules() in E:\public\clrmd2.0\src\Microsoft.Diagnostics.Runtime\src\DataTargets\DataTarget.cs:line 207
       at Microsoft.Diagnostics.Runtime.DataTarget.GetOrCreateClrVersions() in E:\public\clrmd2.0\src\Microsoft.Diagnostics.Runtime\src\DataTargets\DataTarget.cs:line 150
       at Microsoft.Diagnostics.Runtime.DataTarget.DebugOnlyLoadLazyValues() in E:\public\clrmd2.0\src\Microsoft.Diagnostics.Runtime\src\DataTargets\DataTarget.cs:line 131
       at Microsoft.Diagnostics.Runtime.DataTarget..ctor(IDataReader reader) in E:\public\clrmd2.0\src\Microsoft.Diagnostics.Runtime\src\DataTargets\DataTarget.cs:line 68
       at Microsoft.Diagnostics.Runtime.DataTarget.LoadCoreDump(String path) in E:\public\clrmd2.0\src\Microsoft.Diagnostics.Runtime\src\DataTargets\DataTarget.cs:line 257
    ```

**Comment by NextTurn** [comment]
> When `slot` is -1 (I don't know how this is possible), it turns into an OverflowException.

I can reproduce this.

**Comment by leculver** [comment]
@swift-kim Please open multiple issues in the future.  That makes it easier to track work and to make sure I don't close an issue before it's fixed.

**Comment by leculver** [comment]
These three issues _should_ be fixed in: https://www.nuget.org/packages/Microsoft.Diagnostics.Runtime/2.0.0-beta.20220.3

Please let me know if there's still something wrong.  (Also please open a new issue for each individual exception/bug you find still reproducing.)  Thanks!

**Comment by swift-kim** [comment]
Thanks!
