### ISSUE TITLE
SymbolServerLocator.FindBinary can not create folder for the downloaded assembly 

### ISSUE THREAD

**Issue by ViacheslavAfanasyev** [microsoft/clrmd#669]
2.0.0-beta.20272.1

The following line of the code fails with downloading mscordacwks:

`this.DataTarget.BinaryLocator.FindBinary(this.DataTarget.ClrVersions[0].DacInfo.PlatformAgnosticFileName, this.DataTarget.ClrVersions[0].DacInfo.IndexTimeStamp, this.DataTarget.ClrVersions[0].DacInfo.IndexFileSize, checkProperties: false);`

The following exception appears:

"Could not find a part of the path 'C:\\Users\\Slava\\AppData\\Local\\Temp\\symbols\\mscordacwks_amd64_amd64_4.8.4150.00.dll\\5e176fc2ac1000\\mscordacwks_amd64_amd64_4.8.4150.00.dll'."

at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
at System.Threading.Tasks.Task`1.get_Result()
at Microsoft.Diagnostics.Runtime.Implementation.SymbolServerLocator.FindBinary(String fileName, Int32 buildTimeStamp, Int32 imageSize, Boolean checkProperties) 

In case I manually create mscordacwks_amd64_amd64_4.8.4150.00.dll\\5e176fc2ac1000\\ inside C:\\Users\\Slava\\AppData\\Local\\Temp\\symbols\\, the assembly is downloaded.

**Comment by leculver** [comment]
@ViacheslavAfanasyev This should hopefully be fixed in https://www.nuget.org/packages/Microsoft.Diagnostics.Runtime/2.0.0-beta.20273.1.  Thanks @NextTurn !
