### ISSUE TITLE
Exception when disposing on Windows 7

### ISSUE THREAD

**Issue by ciuly** [microsoft/clrmd#824]
Installed latest 2.0.142701 targeting 4.7.2 (al;though I see that doesn't count much in this case)
Running on windows 7 I get the following:

```
Exception thrown: 'System.EntryPointNotFoundException' in Microsoft.Diagnostics.Runtime.dll
Exception thrown: 'System.EntryPointNotFoundException' in Microsoft.Diagnostics.Runtime.dll
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>Procura.WindowsService.CCNetIntegrationAgent.exe</AppDomain><Exception><ExceptionType>System.EntryPointNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Unable to find an entry point named 'PssFreeSnapshot' in DLL 'kernel32.dll'.</Message><StackTrace>   at Microsoft.Diagnostics.Runtime.WindowsProcessDataReader.PssFreeSnapshot(IntPtr ProcessHandle, IntPtr SnapshotHandle)
   at Microsoft.Diagnostics.Runtime.WindowsProcessDataReader.Dispose(Boolean _) in F:\workspace\_work\1\s\src\Microsoft.Diagnostics.Runtime\src\DataReaders\Windows\WindowsProcessDataReader.cs:line 86
   at Microsoft.Diagnostics.Runtime.WindowsProcessDataReader.Finalize() in F:\workspace\_work\1\s\src\Microsoft.Diagnostics.Runtime\src\DataReaders\Windows\WindowsProcessDataReader.cs:line 115</StackTrace><ExceptionString>System.EntryPointNotFoundException: Unable to find an entry point named 'PssFreeSnapshot' in DLL 'kernel32.dll'.
   at Microsoft.Diagnostics.Runtime.WindowsProcessDataReader.PssFreeSnapshot(IntPtr ProcessHandle, IntPtr SnapshotHandle)
   at Microsoft.Diagnostics.Runtime.WindowsProcessDataReader.Dispose(Boolean _) in F:\workspace\_work\1\s\src\Microsoft.Diagnostics.Runtime\src\DataReaders\Windows\WindowsProcessDataReader.cs:line 86
   at Microsoft.Diagnostics.Runtime.WindowsProcessDataReader.Finalize() in F:\workspace\_work\1\s\src\Microsoft.Diagnostics.Runtime\src\DataReaders\Windows\WindowsProcessDataReader.cs:line 115</ExceptionString></Exception></TraceRecord>
Topshelf.Hosts.ConsoleRunHost Critical: 0 : The service threw an unhandled exception, System.EntryPointNotFoundException: Unable to find an entry point named 'PssFreeSnapshot' in DLL 'kernel32.dll'.
   at Microsoft.Diagnostics.Runtime.WindowsProcessDataReader.PssFreeSnapshot(IntPtr ProcessHandle, IntPtr SnapshotHandle)
   at Microsoft.Diagnostics.Runtime.WindowsProcessDataReader.Dispose(Boolean _) in F:\workspace\_work\1\s\src\Microsoft.Diagnostics.Runtime\src\DataReaders\Windows\WindowsProcessDataReader.cs:line 86
   at Microsoft.Diagnostics.Runtime.WindowsProcessDataReader.Finalize() in F:\workspace\_work\1\s\src\Microsoft.Diagnostics.Runtime\src\DataReaders\Windows\WindowsProcessDataReader.cs:line 115

```

the referred function PssFreeSnapshot is only defined on win 8.1 from what I see in MSDN.

repro code would probably help:
```
            using (var target = DataTarget.CreateSnapshotAndAttach(Process.GetCurrentProcess().Id))
            {
                ClrRuntime runtime = target.ClrVersions.First().CreateRuntime();

                var threadIdAndNames = runtime.Heap.EnumerateObjects()
                    .Where(o => o.Type.Equals(typeof(Thread)))
                    .ToDictionary(k => k.ReadField<int>("m_ManagedThreadId"), v => v.ReadStringField("m_Name"));

                foreach (ClrThread thread in runtime.Threads)
                {
                    LogThreadStatus(thread, fullStackTrace, threadIdAndNames);
                }
            }
```

**Comment by leculver** [comment]
Ah yes, `CreateSnapshotAndAttach` is only supported on Win8.1 and beyond.  I'll leave this issue open to add a better exception when this is called.  We might be able to use the Linux codepath (taking a temporary crash dump) but that would have vastly different performance characteristics on different versions of windows...  Not sure if that's the right path here or not.
