### ISSUE TITLE
NRE in LockInspection.SetThreadWaiters during DesktopGCHeap.InitLockInspection

### ISSUE THREAD

**Issue by discostu105** [microsoft/clrmd#85]
```
ERROR: Exception happened: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Diagnostics.Runtime.Desktop.LockInspection.SetThreadWaiters()
   at Microsoft.Diagnostics.Runtime.Desktop.LockInspection.InitLockInspection()
   at Microsoft.Diagnostics.Runtime.Desktop.DesktopGCHeap.InitLockInspection()
   at Microsoft.Diagnostics.Runtime.Desktop.DesktopThread.get_BlockingObjects()
   at SuperDump.Analyzers.ThreadAnalyzer.GetBlockingObjects() in C:\workspaces\superdump-internal\src\SuperDump\Analyzers\ThreadAnalyzer.cs:line 44
   at SuperDump.Analyzers.ThreadAnalyzer..ctor(DumpContext context) in C:\workspaces\superdump-internal\src\SuperDump\Analyzers\ThreadAnalyzer.cs:line 36
   at SuperDump.Program.Main(String[] args) in C:\workspaces\superdump-internal\src\SuperDump\Program.cs:line 74
```

Here is the calling code: https://github.com/Dynatrace/superdump/blob/master/src/SuperDump/Analyzers/ThreadAnalyzer.cs#L44

This happens with a specific crashdump, which I cannot share for privacy reasons. The dump is a *User mini dump*.

CLRMD version: "0.9.170809.03".

By the way, I've noticed that since I've upgraded from "0.8.31-beta" to "0.9.170809.03", that `ClrHeap.CanWalkHeap` returns true in cases where it returned false before. Not sure if this was an intended change, but it led to a couple of bugs in my code. Might also be related to the appearance of this bug.

This is the `heap` object at the time of the NRE. Can this be valid if `TotalHeapSize` is zero and `CanWalkHeap` is true?
![image](https://user-images.githubusercontent.com/10918780/30054693-2f669072-922d-11e7-8d71-b3d0430d84ce.png)

**Comment by leculver** [comment]
Hello!  Unfortunately this feature is slated for removal in ClrMD 2.0, if you need to continue using this feature the migration path forward will be to copy the code for it into your project, at which point you will be able to fix bugs here.  Sorry for the trouble!
