### ISSUE TITLE
ServerNotAvailableException

### ISSUE THREAD

**Issue by sungam3r** [microsoft/clrmd#876]
```
Microsoft.Diagnostics.NETCore.Client.ServerNotAvailableException : Process 28900 not running compatible .NET Core runtime.
   at Microsoft.Diagnostics.NETCore.Client.IpcClient.GetTransport(Int32 processId)
   at Microsoft.Diagnostics.NETCore.Client.IpcClient.SendMessage(Int32 processId, IpcMessage message)
   at Microsoft.Diagnostics.NETCore.Client.DiagnosticsClient.WriteDump(DumpType dumpType, String dumpPath, Boolean logDumpGeneration)
   at Microsoft.Diagnostics.Runtime.LinuxSnapshotTarget.CreateSnapshotFromProcess(Int32 pid)
   at Microsoft.Diagnostics.Runtime.DataTarget.CreateSnapshotAndAttach(Int32 processId)
```

OSDescription: Linux 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 11 19:12:04 EDT 2020
FrameworkDescription: .NET Core 3.1.10
OSArchitecture: X64
ProcessArchitecture: X64

Is this platform really not supported?

**Comment by leculver** [comment]
@mikem8361 Can you comment on what versions of .Net Core are supported by LinuxSnapshotTarget?

**Comment by mikem8361** [comment]
It should be supported on 3.1.10 Linux x64.
