### ISSUE TITLE
IOException when import some core dump

### ISSUE THREAD

**Issue by catstrike** [microsoft/clrmd#931]
Trying to import the dump with the most recent version of ClrMD and getting IOException.

```
// Example

var dataTarget = DataTarget.LoadDump(fileName);
var count = dataTarget.ClrVersions.Length;
```

Stack trace:
```
  at Microsoft.Diagnostics.Runtime.Utilities.Reader.Read[T](UInt64& position) in D:\workspace\_work\1\s\src\Microsoft.Diagnostics.Runtime\src\Linux\ElfReader.cs:line 55
  at Microsoft.Diagnostics.Runtime.Utilities.ElfDynamicSection..ctor(Reader reader, Boolean is64Bit, UInt64 address, UInt64 size) in D:\workspace\_work\1\s\src\Microsoft.Diagnostics.Runtime\src\Linux\ElfDynamicSection.cs:line 21
  at Microsoft.Diagnostics.Runtime.Utilities.ElfFile.get_DynamicSection() in D:\workspace\_work\1\s\src\Microsoft.Diagnostics.Runtime\src\Linux\ElfFile.cs:line 79
  at Microsoft.Diagnostics.Runtime.CoredumpReader.TryGetSymbolAddress(UInt64 baseAddress, String name, UInt64& offset) in D:\workspace\_work\1\s\src\Microsoft.Diagnostics.Runtime\src\DataReaders\Core\CoreDumpReader.cs:line 176
  at Microsoft.Diagnostics.Runtime.DataTarget.GetOrCreateClrVersions() in D:\workspace\_work\1\s\src\Microsoft.Diagnostics.Runtime\src\DataTargets\DataTarget.cs:line 182
  at Microsoft.Diagnostics.Runtime.DataTarget.get_ClrVersions() in D:\workspace\_work\1\s\src\Microsoft.Diagnostics.Runtime\src\DataTargets\DataTarget.cs:line 154
```

The older version of ClrMD would catch the exception in `CoreDumpReader.TryGetSymbolAddress` method, but after the commit "4f366cb Expose ELF coredump reader as public" it's no longer the case.

Dump example:
https://drive.google.com/file/d/126MFSemzfiueRbrK9OEtUvvNzRXIdUCV/view

**Comment by kkokosa** [comment]
Exactly the same issue here.
