### ISSUE TITLE
System.AccessViolationException when reading dump 

### ISSUE THREAD

**Issue by PhDuck** [microsoft/clrmd#947]
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at Microsoft.Diagnostics.Runtime.Windows.CacheNativeMethods+Memory.memcpy(IntPtr, UIntPtr, UIntPtr)
--------------------------------
   at Microsoft.Diagnostics.Runtime.Windows.ArrayPoolBasedCacheEntry.CopyDataFromPage(Microsoft.Diagnostics.Runtime.Windows.CachePage`1<Byte[]>, IntPtr, UInt32, UInt32)
   at Microsoft.Diagnostics.Runtime.Windows.CacheEntryBase`1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadPageDataFromOffset(Int32, UInt32, UInt32, IntPtr, System.Func`3<UIntPtr,UInt32
,UInt32>)
   at Microsoft.Diagnostics.Runtime.Windows.CacheEntryBase`1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetDataForAddress(UInt64, UInt32, IntPtr, UInt32 ByRef)
   at Microsoft.Diagnostics.Runtime.Windows.CachedMemoryReader.TryReadMemory(UInt64, Int32, IntPtr)
   at Microsoft.Diagnostics.Runtime.Windows.CachedMemoryReader.Read(UInt64, System.Span`1<Byte>)
   at Microsoft.Diagnostics.Runtime.MemoryReader.MoveToPage(UInt64)
   at Microsoft.Diagnostics.Runtime.MemoryReader.ReadPtr(UInt64, UInt64 ByRef)
   at Microsoft.Diagnostics.Runtime.Implementation.ClrmdSegment+<EnumerateObjects>d__39.MoveNext()
   at System.Linq.Enumerable+SelectManySingleSelectorIterator`2[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.Diagnostics.Runtime.ClrObject, Microsoft.Diagnostics.Runtime, Version
=2.0.4.26801, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at System.Linq.Enumerable+WhereEnumerableIterator`1[[Microsoft.Diagnostics.Runtime.ClrObject, Microsoft.Diagnostics.Runtime, Version=2.0.4.26801, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at MemAna.Analysis.Rules.StringDuplication.ObjectWalk()
   at MemAna.Analysis.Rules.StringDuplication.ExecuteImpl()
   at MemAna.Analysis.AnalysisRule+<>c__DisplayClass6_0.<Execute>b__0()
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__277_0(System.Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

OS: Windows Server 2016 (Azure VM if that matters)
14393.4402.amd64fre.rs1_release.210426-1725
CoreCLR Version: 5.0.921.35908
.NET Version: 5.0.9
X64
Microsoft.Diagnostics.Runtime: 2.0.226801

Dump info:
.NET 4.8 X64
32GB

Seems to crash when hitting around 2.3 GB of memory usage, which seems a bit strange.

**Comment by ryanmolden** [comment]
@PhDuck thanks for the report (I know its quite old, I never use GitHub so I am just seeing this :().

I wrote the code in question so I can certainly take a look, though it looks like @catstrike may have found the issue if the segment size is > int32.MaxValue.

One alternative you could try, though it is Windows only and requires enabling a specific setting, would be to use the AWE setting instead of the array style caching.

I think you enable this by setting the CacheOptions to UseOSMemoryFeatures (the ones passed in to the minidump ctor) and then setting up Windows to enable locking pages in memory (requires a reboot):

https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/enable-the-lock-pages-in-memory-option-windows?view=sql-server-ver16
