### ISSUE TITLE
DataTarget.CreateSnapshotAndAttach error: Unable to find an entry point named 'PssCaptureSnapshot' in DLL 'kernel32.dll'

### ISSUE THREAD

**Issue by R4ND3LL** [microsoft/clrmd#953]
This line of code produces the error below:
``
  var target = DataTarget.CreateSnapshotAndAttach(Process.GetCurrentProcess().Id);
``

**System.EntryPointNotFoundException: Unable to find an entry point named 'PssCaptureSnapshot' in DLL 'kernel32.dll'.**

Unable to find an entry point named 'PssCaptureSnapshot' in DLL 'kernel32.dll'.
       at Microsoft.Diagnostics.Runtime.WindowsProcessDataReader.PssCaptureSnapshot(IntPtr ProcessHandle, PSS_CAPTURE_FLAGS CaptureFlags, Int32 ThreadContextFlags, IntPtr& SnapshotHandle)
   at Microsoft.Diagnostics.Runtime.WindowsProcessDataReader..ctor(Int32 processId, WindowsProcessDataReaderMode mode)
   at Microsoft.Diagnostics.Runtime.DataTarget.CreateSnapshotAndAttach(Int32 processId)
   at ServerAdminPlugin.StackTraceAnalyzer.GetAllStackTraces()

**Environment:** .NET 5 app running on Windows Server 2008 R2 Standard, with, among other things, latest .NET 5 SDK installed.

Same code works on dev machine (Win 10)

**Comment by R4ND3LL** [comment]
I may have answered my own question.  Microsoft states that this function is only supported on:

<html>
<body>


Minimum supported client | Windows 8.1 [desktop apps only]
-- | --
Minimum supported server | Windows Server 2012 R2 [desktop apps only]


</body>
</html>

Researching elsewhere, I found this function was only included on kernel32.dll version 6.3+.

Would be nice if this was noted somewhere in the docs around CreateSnapshotAndAttach use on Windows.

**Comment by liudonghua123** [comment]
I encountered the same problems when back port cpython 3.12 to windows 7, and I rewrite the usage of `PssCaptureSnapshot`.

See https://github.com/liudonghua123/windows-python-installer/commit/d1ad543a51ce00e574b9aeeb768f7fa1c5020a0b, https://github.com/adang1345/PythonWin7/blob/master/patches/restore-win7-handling.patch.
